### ISSUE TITLE
SonarQube v7 compatibility

### ISSUE THREAD

**Issue by aairey** [OtherDevOpsGene/zap-sonar-plugin#40]
When running the plugin on SonarQube 7.x we get the following stacktrace:
```
ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin ZAP [zap]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to register extension org.sonar.zaproxy.base.ZapMetrics from plugin 'zap'
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:242)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:119)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:74)
	... 9 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/measures/Formula
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.picocontainer.injectors.AdaptingInjection$2.run(AdaptingInjection.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.picocontainer.injectors.AdaptingInjection.injectionFieldAnnotated(AdaptingInjection.java:209)
	at org.picocontainer.injectors.AdaptingInjection.fieldAnnotatedInjectionAdapter(AdaptingInjection.java:188)
	at org.picocontainer.injectors.AdaptingInjection.createComponentAdapter(AdaptingInjection.java:57)
	at org.picocontainer.behaviors.AbstractBehaviorFactory.createComponentAdapter(AbstractBehaviorFactory.java:44)
	at org.picocontainer.behaviors.OptInCaching.createComponentAdapter(OptInCaching.java:45)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:536)
	at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
	at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:240)
	... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.measures.Formula
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted
```

For compatibility with SonarQube 7.x we should fix some imports.

`org.sonar.api.measures.Formula` no longer exists in SonarQube 7.x.
See http://javadocs.sonarsource.org/7.3/apidocs/org/sonar/api/measures/package-tree.html

I know the target release is LTS (v6 currently) but it would be nice to already support running the plugin on the next version.

**Comment by pethers** [comment]
Happy to help out testing it, have zap report https://www.hack23.com/jenkins/view/SystemSecurityTest/job/zaptest/Security_20Scan_20Report/ and sonarqube 7.3 https://www.hack23.com/sonar/dashboard?id=com.hack23.cia%3Acia-all , so would be nice if it worked.

**Comment by parrot55** [comment]
LTS 7.9 is out. An update would be appreciated. Can I help?

**Comment by pethers** [comment]
Created a fork https://github.com/Hack23/zap-sonar-plugin, works with 7.9. Same as https://github.com/Coveros/zap-sonar-plugin/pull/41, but have got no response here so prepared to release it with other groupId.

**Comment by OtherDevOpsGene** [comment]
I'll commit to getting a release out this week for LTS 7.9 and I am working on getting releases onto a regular schedule. Sorry for the delays.

**Comment by OtherDevOpsGene** [comment]
I think this should be done. 1.2.0 is released. It works on my (7.9 LTS) machine 😄
