### ISSUE TITLE
Update to current dependencies

### ISSUE THREAD

**Issue by OtherDevOpsGene** [OtherDevOpsGene/zap-sonar-plugin#49]
Update the dependencies, parent, etc. to current

**Comment by pethers** [comment]
Startup issues , just tested latest main https://github.com/OtherDevOpsGene/zap-sonar-plugin  on sonarqube-8.5.1.38104

'''java.lang.IllegalStateException: Fail to load plugin ZAP Plugin for SonarQube [zap]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:80)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:555)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
        at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)'''
